site_name: "Cibersec Portfolio"
site_description: "Lab writeups and cybersecurity projects
site_author: "Antonio Cavazos"

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_style: github-dark
  - pymdownx.superfences

# Menú organizado por secciones (Corregido con espacios hacia la derecha)
nav:
  - Inicio: index.md
  - Laboratories:
      - Laboratories: docs/laboratories/index.md
       - Laboratories: laboratories/index.md
      - Lab 1: docs/laboratories/lab-01/index.md
  - CTF:
      - CTF: ctf/index.md
      - HackTheBox: ctf/htb-machine-1.md
      - TryHackMe: ctf/tryhackme-room-1.md
  - Proyectos:
      - Proyectos: proyectos/index.md
      - Proyecto 1: proyectos/proyecto-1.md
      - Proyecto 2: proyectos/proyecto-2.md
  - Sobre mí: sobre-mi.md
