name: Desplegar Portafolio MkDocs
on:
  push:
    branches:
      - main # Se activa cuando subes notas desde Obsidian a main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Instalar MkDocs y Tema Material
        run: |
          pip install mkdocs-material

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Compilar el sitio web
        run: mkdocs build

      - name: Subir artefacto de la web
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
